Fluke CDA: make partitioned disk image for eMMC on Nighthawk, instead of ubifs image for qspi flash.

diff --git a/common/publish b/common/publish
--- a/common/publish
+++ b/common/publish
@@ -1,5 +1,6 @@
 #!/bin/bash
 #
+set -e
 
 source ./setup_environment
 
@@ -20,16 +21,12 @@ fi
 if [ ! -d "./targetAux" ]; then
     mkdir ./targetAux
 fi
-echo "Building the ubifs image."
+#echo "Building the ubifs image."
 #sudo ./mkubifs
-cp -p $PROJECT_IMAGES/fluke-full-image-${PROJECT_MACHINE}.ubi ./rootfs/ubi.img
-
-
-echo "Setting image permissions."
-sudo chmod 666 ./rootfs/ubi.img
-sudo chgrp pmengr ./rootfs/ubi.img
-sudo chgrp pmengr ./kernel/zImage
-echo "done!"
+if [ -z "$SKIP_UBIFS" ] 
+then
+	cp -p $PROJECT_IMAGES/fluke-full-image-${PROJECT_MACHINE}.ubi ./rootfs/ubi.img
+fi
 
 echo "Building composite flash images."
 /usr/bin/srec_cat \
@@ -45,16 +42,32 @@ echo "Building composite flash images."
 -Fill 0xff -over ./rootfs/U10.flash \
 -Output ./rootfs/U10.bin -Binary
 echo "U10 done!"
-/usr/bin/srec_cat \
-./rootfs/ubi.img -Binary \
--Output ./rootfs/U11.flash -Motorola --address-length=4 -Data_Only
-/usr/bin/srec_cat ./rootfs/U11.flash -Motorola \
--Fill 0xff -over ./rootfs/U11.flash \
--Output ./rootfs/U11.bin -Binary
-echo "U11 done!"
-chgrp pmengr ./rootfs/U10.bin
-chgrp pmengr ./rootfs/U11.bin
+if [ -z "$SKIP_UBIFS" ] 
+then
+	/usr/bin/srec_cat \
+	./rootfs/ubi.img -Binary \
+	-Output ./rootfs/U11.flash -Motorola --address-length=4 -Data_Only
+	/usr/bin/srec_cat ./rootfs/U11.flash -Motorola \
+	-Fill 0xff -over ./rootfs/U11.flash \
+	-Output ./rootfs/U11.bin -Binary
+	echo "U11 done!"
+fi
 echo "Composite images created!"
+
+
+if [ -z "$SKIP_PMENGR_GROUP" ] 
+then
+	echo "Setting image permissions."
+	if [ -z "$SKIP_UBIFS" ] 
+	then
+		chmod 666 ./rootfs/ubi.img
+		chgrp pmengr ./rootfs/ubi.img
+		chgrp pmengr ./rootfs/U11.bin
+	fi
+	chgrp pmengr ./kernel/zImage
+	chgrp pmengr ./rootfs/U10.bin
+	echo "done!"
+fi
 
 BUILD_DATE=$(date +"%y_%m_%d")
 RELEASE_FOLDER=${BUILD_DATE}_${PROJECT_NAME}
@@ -73,8 +86,13 @@ cp -Rp ./toolchain/* ./release/${RELEASE_FOLDER}/toolchain/
 cp -Rp ./DeviceTree ./release/${RELEASE_FOLDER}/.
 cp -Rp ./loader ./release/${RELEASE_FOLDER}/.
 cp -p ./kernel/zImage ./release/${RELEASE_FOLDER}/zImage/. 
-cp -p ./rootfs/ubi.img ./release/${RELEASE_FOLDER}/rootfs/. 
+if [ -z "$SKIP_UBIFS" ] 
+then
+	cp -p ./rootfs/ubi.img ./release/${RELEASE_FOLDER}/rootfs/. 
+	cp -p ./rootfs/U11.bin ./release/${RELEASE_FOLDER}/U11/. 
+fi
+cp -p $PROJECT_IMAGES/fluke-full-image-${PROJECT_MACHINE}.wic.gz ./release/${RELEASE_FOLDER}/rootfs/ || \
+	echo "Failed to copy fluke-full-image-${PROJECT_MACHINE}.wic.gz to release folder (only used for eMMC root fs)."
 cp -p ./rootfs/U10.bin ./release/${RELEASE_FOLDER}/U10/. 
-cp -p ./rootfs/U11.bin ./release/${RELEASE_FOLDER}/U11/. 
 cp -p ./fpga/* ./release/${RELEASE_FOLDER}/fpga/.
 
